# Generated by Django 5.1.1 on 2024-09-13 09:30
"""Module providing database migrations for employee and department tables."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Database migrations for employee and department tables."""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('address',
                 models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.IntegerField(unique=True)),
                ('branch', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='departments',
                                             to='company.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('phone_number',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email',
                 models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.ForeignKey(null=True,
                                                 on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='employees',
                                                 to='company.department')),
            ],
        ),
    ]
